language: dart
dist: xenial

# Custom configuration
sudo: required
addons:
  apt:
    packages:
      - libstdc++6
env:
  global:
    - FLUTTER_CHANNEL=stable
    - APP=mobile
    - ANDROID_API=28

before_install: cd "CS Mobile/mobile/"

install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get

jobs:
  include:
    - stage: "Analyze Test"
      name: "Static analysis"
      script: flutter analyze --no-current-package lib  
    - stage: "Widget Tests"
      name: "Widget tests"                  
      script: flutter test

stages:
  - "Analyze Test"
  - "Widget Tests"

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - develop

cache:
  bundler: true
  directories:
    - "$HOME/.pub-cache"
