language: dart
dist: xenial

# Custom configuration
sudo: required
addons:
  apt:
    packages:
      - libstdc++6

before_install: cd "CS Mobile/mobile/"

install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get

jobs:
  include:
    - stage: analyze
      name: "Static analysis"
      script: flutter analyze --no-current-package lib  
    - stage: widgets
      name: "Widget tests"                  
      script: flutter test

stages:
  - analyze
  - widgett

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - develop

cache:
  bundler: true
  directories:
    - "$HOME/.pub-cache"
