language: dart
dist: xenial

# Custom configuration
sudo: required
addons:
  apt:
    packages:
      - libstdc++6
env:
  - TEST_SUITE=analyze
  - TEST_SUITE=widget

jobs:
  include:
    - stage: analyze
      name: "Static analysis"
      script: "bundle exec rake analyze:$TEST_SUITE"   
    - stage: widgets
      name: "Widget tests"                  
      script: "bundle exec rake widget:$TEST_SUITE"

stages:
  - analyze
  - widgett

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - develop

cache:
  directories:
    - "$HOME/.pub-cache"
