# Generated by Django 3.0.5 on 2020-05-03 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('vehicle_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='vehicle id')),
                ('registration', models.CharField(editable=False, max_length=10, verbose_name='registration')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('vin', models.CharField(max_length=20, verbose_name='vin')),
                ('model_year', models.CharField(max_length=4, verbose_name='model year')),
                ('colour', models.CharField(max_length=25, verbose_name='colour')),
                ('fuel_type', models.CharField(max_length=10, verbose_name='fuel type')),
                ('power_hp', models.CharField(max_length=4, verbose_name='power hp')),
                ('number_of_doors', models.CharField(choices=[('1', '1 Door'), ('2', '2 Door'), ('3', '3 Door'), ('4', '4 Door'), ('5', '5 Door')], max_length=1, verbose_name='number of doors')),
                ('number_of_seats', models.CharField(choices=[('1', 'Single Seater'), ('2', '2 Seater'), ('3', '3 Seater'), ('4', '4 Seater'), ('5', '5 Seater'), ('6', '6 Seater'), ('7', '7 Seater'), ('8', '8 Seater'), ('9', '9 Seater'), ('10', '10 Seater')], max_length=2, verbose_name='number of seats')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
                ('associated_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
