# Generated by Django 3.0.5 on 2020-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20200503_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='registration',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='registration number'),
        ),
    ]
