# Generated by Django 3.0.5 on 2020-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20200503_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='registration number'),
        ),
    ]
