# Generated by Django 3.0.6 on 2020-05-18 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('title', models.CharField(blank=True, choices=[('mr', 'MR'), ('mrs', 'MRS'), ('miss', 'Miss'), ('ms', 'MS'), ('mx', 'Mx')], max_length=4, verbose_name='title')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='phone number')),
                ('job', models.CharField(blank=True, choices=[('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('operations', 'Operations'), ('quality', 'Quality Control'), ('supervisor', 'Supervisor'), ('marketing', 'Marketing'), ('purchasing', 'Purchasing'), ('software', 'Software Engineer'), ('support', 'I.T. Support'), ('management', 'Management'), ('safety', 'Safety and Environmental')], max_length=15, verbose_name='job')),
                ('company', models.CharField(choices=[('AGL', 'Admiral Group'), ('AA', 'AA Insurance'), ('VEY', 'Veygo')], max_length=3, verbose_name='company')),
                ('status', models.CharField(choices=[('A', 'Authorized'), ('P', 'Pending'), ('R', 'Rejected'), ('V', 'Revoked')], default='P', max_length=1, verbose_name='status')),
                ('admin', models.BooleanField(default=False, verbose_name='admin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
            ],
        ),
    ]
